<?php
return  [
    "Cairo",
    "Ad Daqahliyah",
    "Al Baḩr al Aḩmar",
    "Al Buḩayrah",
    "Al Fayyum",
    "Al Gharbiyah",
    "Al Iskandariyah",
    "Al Ismaٰiliyah",
    "Al Jizah",
    "Al Minya",
    "Al Minufiyah",
    "Al Qalyubiyah",
    "Al Qahirah",
    "Al Uqşur",
    "Al Wadi al Jadid",
    "As Suways",
    "As Sadis min Uktubar",
    "Ash Sharqiyah",
    "Aswan",
    "Asyuţ",
    "Bani Suwayf",
    "Bur Saٰid",
    "Kafr ash Shaykh",
    "Maţruḩ",
    "Shamal Sina'",
    "Suhaj",
    "Ḩulwan"
];
